services:
  unitycode-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unitycode-api
    ports:
      - '8080:8080'
    restart: unless-stopped
  mongo:
    image: mongo:8.0.14-rc0-noble
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local