services:
  unitycode-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unitycode-api
    ports:
      - '${API_PORT}:8080'
    environment:
      - DB_CONNECTION=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DEBUG=${DEBUG}
      - NODE_ENV=${NODE_ENV}
    restart: unless-stopped
    networks:
      - api-network
    depends_on:
      - mongo
  mongo:
    image: mongo:8.0.14-rc0-noble
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - api-network

volumes:
  mongo-data:
    driver: local

networks:
  api-network:
    driver: bridge